# input eight numbers from the user and display all the unique numbers(once)

numbers=[]
number=int(input("enter number:"))
numbers.append(number)
number=int(input("enter number:"))
numbers.append(number)
number=int(input("enter number:"))
numbers.append(number)
number=int(input("enter number:"))
numbers.append(number)
number=int(input("enter number:"))
numbers.append(number)
number=int(input("enter number:"))
numbers.append(number)
number=int(input("enter number:"))
numbers.append(number)
number=int(input("enter number:"))
numbers.append(number)
print((set(numbers)))